spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCjWdqCm8HLXbrNWx0gjRqKUfoDC0JfCLj4erNMUJl+EiB04isHsPhFs0Jbg0erlaqm3RaCmQ9tvHvcLxyt+hbnARhugb3+dTLDyTKHqt8PjbpiYQP7xEuJSzpVB+SOT58A0FXcj4NypQg084e9HN+ZxRCwg1MsC6lFlwxPkUaQ/JHYu/8WCkXerpWNsozCh7x0ChF+H1tNg9K8goB4IebBxeUuiH1WCOE76j62e9un4+6yVg7a1CVsvhT1m76o8kA+WSsXeWcdtJEgz+cAe0NPUpkYibmM4R4iXuaFAogRyIN0QtxTPc+mIP+1jQvJ90KnEzpgaixNyzx95ZxSoz3yPpENKRR6SlRk2+vVSSQzqWQQP5DH9UoKn6W11EPML3I='

token:
  expiration_time: 86400000
  secret: '{cipher}AQDF2TKKPqKk85/pQdvp4Rgpn+NdWDEe8DcQBAc4G7gLyr2zkMw5hcDHUlyvlcO4/TCAnnUIXlSQ2x3SmnlBtP5QHPsyX5t3wuA6HIiCS4qu9Fm8/9enN6C+sStaJy64uPgy8sbxl5701uEUl7KuVou43apqpeMI01txeaNCXpjDi6AfjOINapnRNIaZqQoTMIEdlWNCrMj+ErIr4a2uPjAQIRUdCjOD9LC0l3whF8Ml+uUMk4So3tX1VlXv5gcLIgI6tGFF/ZlB9YIRpaiWedtfjn+NFbnoehMISaWc0Cq3TScVKwE5xa/yzvC0yH2O0zTeHvR1dk8JvitrQEkAEl/a/j8HTuXhuEOP5DdrBBWsm6HgjAPJO/dyj7owGtlCOxtsoXzI+43FHuPS2EE7+tMw'

gateway:
  ip: 192.168.50.129

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders