spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCjWdqCm8HLXbrNWx0gjRqKUfoDC0JfCLj4erNMUJl+EiB04isHsPhFs0Jbg0erlaqm3RaCmQ9tvHvcLxyt+hbnARhugb3+dTLDyTKHqt8PjbpiYQP7xEuJSzpVB+SOT58A0FXcj4NypQg084e9HN+ZxRCwg1MsC6lFlwxPkUaQ/JHYu/8WCkXerpWNsozCh7x0ChF+H1tNg9K8goB4IebBxeUuiH1WCOE76j62e9un4+6yVg7a1CVsvhT1m76o8kA+WSsXeWcdtJEgz+cAe0NPUpkYibmM4R4iXuaFAogRyIN0QtxTPc+mIP+1jQvJ90KnEzpgaixNyzx95ZxSoz3yPpENKRR6SlRk2+vVSSQzqWQQP5DH9UoKn6W11EPML3I='

token:
  expiration_time: 86400000
  secret: '{cipher}AQAM4/va+Si8giNBQMeqx/ZxD0DfphLCRygXHjU0wuKNgvPLHEDSRmfRdBaOperBpNeNmSIGnXRAt9vr1FOqbMk+uBnq3lODhEQyXRLvJYC7NlDrxXdGEXar1wDbo2WFXs6jQYenchdtHNismn+QlGW1xJMdIGWGC42vtA4HBhWgtoCb2Wr6CbIohtiGdTx2OFcYMif/D0JdzcQjeoV0mKYjdJZo35hLFiCg1yvEKt2XIjATkalsMDqW8kyKIjD2luQBI1x2adjVRkyWWYLNA3BwAHroQRYRK3v8Zpd/wpP9eHJ7qLqtN8kXU/fWqnkAxHIBRhMKbm3o/qInG2o3f/w7Wk8Ix9h7X7ORIU0+LfHjfLsdp4m8so4Pu+h9Ek9I0sCFozKZjp0SmlFgU9Qhg5jJ'

gateway:
  ip: 192.168.50.129


order_service:
  url: http://127.0.0.1.8000/order-service/%s/orders