spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCjWdqCm8HLXbrNWx0gjRqKUfoDC0JfCLj4erNMUJl+EiB04isHsPhFs0Jbg0erlaqm3RaCmQ9tvHvcLxyt+hbnARhugb3+dTLDyTKHqt8PjbpiYQP7xEuJSzpVB+SOT58A0FXcj4NypQg084e9HN+ZxRCwg1MsC6lFlwxPkUaQ/JHYu/8WCkXerpWNsozCh7x0ChF+H1tNg9K8goB4IebBxeUuiH1WCOE76j62e9un4+6yVg7a1CVsvhT1m76o8kA+WSsXeWcdtJEgz+cAe0NPUpkYibmM4R4iXuaFAogRyIN0QtxTPc+mIP+1jQvJ90KnEzpgaixNyzx95ZxSoz3yPpENKRR6SlRk2+vVSSQzqWQQP5DH9UoKn6W11EPML3I='

token:
  expiration_time: 86400000
  secret: '{cipher}AQB60mRnv+wYKW8f9drMF7n80s0dsRc/LmcVgK5D5o7L6khKK/AMzjTsX3aVATezViZMP9d04BkSp8e/V+SIU0oILMJOEaC9LxSBvKWEX/Osy8lIBMegjXgaukY5U5qewES9qkknE3tAaiHtfb9eG5A9/W+FwtNrq4Vb4MCQbrPnJ6ELLwiCOcWq9VtOwvMaCr7YT+dgZ4L2oYTZ2eQoO+L7ckAh0ec6UeTrF/aM0iLZPAukwBI7djBnOOjrdUqEWr5bCOlP1rgw4TWYuZ9TSGZ9R4ONQxzsrq7eYnr6fW4G8iLYorwKSQqKtX8RtIxpsXAy9fOqe5ENRV0xnEgrb1S7qEfCHji6PKyNpYLFxKLFhMZf5RtrbgGLxMOq9UKQGPCRlSeYzxwK5qFotn584q2UlD/ioArIvv7Qy0152I5Mcg=='

gateway:
  ip: 192.168.50.129

order_service:
  url: http://127.0.0.1.8000/order-service/%s/orders